organizations:
    foo:
        teams:
            bar:
                members:
                    members:
                        - 'one'
                    admins:
                        - 'one'
                    banned:
                        - 'one'
                permission: PUSH
                repositories:
                    - 'one'
                    - 'two'
                exclusions:
                    - 'one'
                    - 'two'
                overrides:
                    one: PULL
                    two: PULL
                    three: PULL
